// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddl.proto

package com.pancakedb.idl;

public interface AlterTableResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.ddl.AlterTableResponse)
    com.google.protobuf.MessageOrBuilder {
}
