// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddl.proto

package com.pancakedb.idl;

/**
 * Protobuf type {@code protos.ddl.CreateTableResponse}
 */
public final class CreateTableResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.ddl.CreateTableResponse)
    CreateTableResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateTableResponse.newBuilder() to construct.
  private CreateTableResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateTableResponse() {
    columnsAdded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateTableResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateTableResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            alreadyExists_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              columnsAdded_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            columnsAdded_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        columnsAdded_ = columnsAdded_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pancakedb.idl.Ddl.internal_static_protos_ddl_CreateTableResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pancakedb.idl.Ddl.internal_static_protos_ddl_CreateTableResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pancakedb.idl.CreateTableResponse.class, com.pancakedb.idl.CreateTableResponse.Builder.class);
  }

  public static final int ALREADY_EXISTS_FIELD_NUMBER = 1;
  private boolean alreadyExists_;
  /**
   * <code>bool already_exists = 1;</code>
   * @return The alreadyExists.
   */
  @java.lang.Override
  public boolean getAlreadyExists() {
    return alreadyExists_;
  }

  public static final int COLUMNS_ADDED_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList columnsAdded_;
  /**
   * <code>repeated string columns_added = 2;</code>
   * @return A list containing the columnsAdded.
   */
  public com.google.protobuf.ProtocolStringList
      getColumnsAddedList() {
    return columnsAdded_;
  }
  /**
   * <code>repeated string columns_added = 2;</code>
   * @return The count of columnsAdded.
   */
  public int getColumnsAddedCount() {
    return columnsAdded_.size();
  }
  /**
   * <code>repeated string columns_added = 2;</code>
   * @param index The index of the element to return.
   * @return The columnsAdded at the given index.
   */
  public java.lang.String getColumnsAdded(int index) {
    return columnsAdded_.get(index);
  }
  /**
   * <code>repeated string columns_added = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the columnsAdded at the given index.
   */
  public com.google.protobuf.ByteString
      getColumnsAddedBytes(int index) {
    return columnsAdded_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alreadyExists_ != false) {
      output.writeBool(1, alreadyExists_);
    }
    for (int i = 0; i < columnsAdded_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, columnsAdded_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alreadyExists_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, alreadyExists_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < columnsAdded_.size(); i++) {
        dataSize += computeStringSizeNoTag(columnsAdded_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getColumnsAddedList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pancakedb.idl.CreateTableResponse)) {
      return super.equals(obj);
    }
    com.pancakedb.idl.CreateTableResponse other = (com.pancakedb.idl.CreateTableResponse) obj;

    if (getAlreadyExists()
        != other.getAlreadyExists()) return false;
    if (!getColumnsAddedList()
        .equals(other.getColumnsAddedList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALREADY_EXISTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlreadyExists());
    if (getColumnsAddedCount() > 0) {
      hash = (37 * hash) + COLUMNS_ADDED_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsAddedList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.CreateTableResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.CreateTableResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.CreateTableResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pancakedb.idl.CreateTableResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.ddl.CreateTableResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.ddl.CreateTableResponse)
      com.pancakedb.idl.CreateTableResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pancakedb.idl.Ddl.internal_static_protos_ddl_CreateTableResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pancakedb.idl.Ddl.internal_static_protos_ddl_CreateTableResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pancakedb.idl.CreateTableResponse.class, com.pancakedb.idl.CreateTableResponse.Builder.class);
    }

    // Construct using com.pancakedb.idl.CreateTableResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      alreadyExists_ = false;

      columnsAdded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pancakedb.idl.Ddl.internal_static_protos_ddl_CreateTableResponse_descriptor;
    }

    @java.lang.Override
    public com.pancakedb.idl.CreateTableResponse getDefaultInstanceForType() {
      return com.pancakedb.idl.CreateTableResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.pancakedb.idl.CreateTableResponse build() {
      com.pancakedb.idl.CreateTableResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pancakedb.idl.CreateTableResponse buildPartial() {
      com.pancakedb.idl.CreateTableResponse result = new com.pancakedb.idl.CreateTableResponse(this);
      int from_bitField0_ = bitField0_;
      result.alreadyExists_ = alreadyExists_;
      if (((bitField0_ & 0x00000001) != 0)) {
        columnsAdded_ = columnsAdded_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.columnsAdded_ = columnsAdded_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pancakedb.idl.CreateTableResponse) {
        return mergeFrom((com.pancakedb.idl.CreateTableResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pancakedb.idl.CreateTableResponse other) {
      if (other == com.pancakedb.idl.CreateTableResponse.getDefaultInstance()) return this;
      if (other.getAlreadyExists() != false) {
        setAlreadyExists(other.getAlreadyExists());
      }
      if (!other.columnsAdded_.isEmpty()) {
        if (columnsAdded_.isEmpty()) {
          columnsAdded_ = other.columnsAdded_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureColumnsAddedIsMutable();
          columnsAdded_.addAll(other.columnsAdded_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pancakedb.idl.CreateTableResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pancakedb.idl.CreateTableResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean alreadyExists_ ;
    /**
     * <code>bool already_exists = 1;</code>
     * @return The alreadyExists.
     */
    @java.lang.Override
    public boolean getAlreadyExists() {
      return alreadyExists_;
    }
    /**
     * <code>bool already_exists = 1;</code>
     * @param value The alreadyExists to set.
     * @return This builder for chaining.
     */
    public Builder setAlreadyExists(boolean value) {
      
      alreadyExists_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool already_exists = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlreadyExists() {
      
      alreadyExists_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList columnsAdded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureColumnsAddedIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        columnsAdded_ = new com.google.protobuf.LazyStringArrayList(columnsAdded_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @return A list containing the columnsAdded.
     */
    public com.google.protobuf.ProtocolStringList
        getColumnsAddedList() {
      return columnsAdded_.getUnmodifiableView();
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @return The count of columnsAdded.
     */
    public int getColumnsAddedCount() {
      return columnsAdded_.size();
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @param index The index of the element to return.
     * @return The columnsAdded at the given index.
     */
    public java.lang.String getColumnsAdded(int index) {
      return columnsAdded_.get(index);
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the columnsAdded at the given index.
     */
    public com.google.protobuf.ByteString
        getColumnsAddedBytes(int index) {
      return columnsAdded_.getByteString(index);
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @param index The index to set the value at.
     * @param value The columnsAdded to set.
     * @return This builder for chaining.
     */
    public Builder setColumnsAdded(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnsAddedIsMutable();
      columnsAdded_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @param value The columnsAdded to add.
     * @return This builder for chaining.
     */
    public Builder addColumnsAdded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnsAddedIsMutable();
      columnsAdded_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @param values The columnsAdded to add.
     * @return This builder for chaining.
     */
    public Builder addAllColumnsAdded(
        java.lang.Iterable<java.lang.String> values) {
      ensureColumnsAddedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, columnsAdded_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearColumnsAdded() {
      columnsAdded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns_added = 2;</code>
     * @param value The bytes of the columnsAdded to add.
     * @return This builder for chaining.
     */
    public Builder addColumnsAddedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureColumnsAddedIsMutable();
      columnsAdded_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.ddl.CreateTableResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.ddl.CreateTableResponse)
  private static final com.pancakedb.idl.CreateTableResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pancakedb.idl.CreateTableResponse();
  }

  public static com.pancakedb.idl.CreateTableResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTableResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateTableResponse>() {
    @java.lang.Override
    public CreateTableResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateTableResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateTableResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTableResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pancakedb.idl.CreateTableResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

