// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddl.proto

package com.pancakedb.idl;

public final class Ddl {
  private Ddl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ddl_CreateTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ddl_CreateTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ddl_CreateTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ddl_CreateTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ddl_DropTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ddl_DropTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ddl_DropTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ddl_DropTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ddl_GetSchemaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ddl_GetSchemaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ddl_GetSchemaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ddl_GetSchemaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tddl.proto\022\nprotos.ddl\032\014schema.proto\"\273\001" +
      "\n\022CreateTableRequest\022\022\n\ntable_name\030\001 \001(\t" +
      "\022%\n\006schema\030\002 \001(\0132\025.protos.schema.Schema\022" +
      "7\n\004mode\030\003 \001(\0162).protos.ddl.CreateTableRe" +
      "quest.SchemaMode\"1\n\nSchemaMode\022\022\n\016FAIL_I" +
      "F_EXISTS\020\000\022\017\n\013OK_IF_EXACT\020\001\"-\n\023CreateTab" +
      "leResponse\022\026\n\016already_exists\030\001 \001(\010\"&\n\020Dr" +
      "opTableRequest\022\022\n\ntable_name\030\001 \001(\t\"\023\n\021Dr" +
      "opTableResponse\"&\n\020GetSchemaRequest\022\022\n\nt" +
      "able_name\030\001 \001(\t\":\n\021GetSchemaResponse\022%\n\006" +
      "schema\030\001 \001(\0132\025.protos.schema.SchemaB\025\n\021c" +
      "om.pancakedb.idlP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pancakedb.idl.SchemaOuterClass.getDescriptor(),
        });
    internal_static_protos_ddl_CreateTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_ddl_CreateTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ddl_CreateTableRequest_descriptor,
        new java.lang.String[] { "TableName", "Schema", "Mode", });
    internal_static_protos_ddl_CreateTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_ddl_CreateTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ddl_CreateTableResponse_descriptor,
        new java.lang.String[] { "AlreadyExists", });
    internal_static_protos_ddl_DropTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_ddl_DropTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ddl_DropTableRequest_descriptor,
        new java.lang.String[] { "TableName", });
    internal_static_protos_ddl_DropTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_ddl_DropTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ddl_DropTableResponse_descriptor,
        new java.lang.String[] { });
    internal_static_protos_ddl_GetSchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protos_ddl_GetSchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ddl_GetSchemaRequest_descriptor,
        new java.lang.String[] { "TableName", });
    internal_static_protos_ddl_GetSchemaResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protos_ddl_GetSchemaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ddl_GetSchemaResponse_descriptor,
        new java.lang.String[] { "Schema", });
    com.pancakedb.idl.SchemaOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
