// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface FieldValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.FieldValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.dml.RepeatedFieldValue list_val = 1;</code>
   * @return Whether the listVal field is set.
   */
  boolean hasListVal();
  /**
   * <code>.protos.dml.RepeatedFieldValue list_val = 1;</code>
   * @return The listVal.
   */
  com.pancakedb.idl.RepeatedFieldValue getListVal();
  /**
   * <code>.protos.dml.RepeatedFieldValue list_val = 1;</code>
   */
  com.pancakedb.idl.RepeatedFieldValueOrBuilder getListValOrBuilder();

  /**
   * <code>string string_val = 2;</code>
   * @return Whether the stringVal field is set.
   */
  boolean hasStringVal();
  /**
   * <code>string string_val = 2;</code>
   * @return The stringVal.
   */
  java.lang.String getStringVal();
  /**
   * <code>string string_val = 2;</code>
   * @return The bytes for stringVal.
   */
  com.google.protobuf.ByteString
      getStringValBytes();

  /**
   * <code>int64 int64_val = 3;</code>
   * @return Whether the int64Val field is set.
   */
  boolean hasInt64Val();
  /**
   * <code>int64 int64_val = 3;</code>
   * @return The int64Val.
   */
  long getInt64Val();

  /**
   * <code>bool bool_val = 4;</code>
   * @return Whether the boolVal field is set.
   */
  boolean hasBoolVal();
  /**
   * <code>bool bool_val = 4;</code>
   * @return The boolVal.
   */
  boolean getBoolVal();

  /**
   * <code>bytes bytes_val = 5;</code>
   * @return Whether the bytesVal field is set.
   */
  boolean hasBytesVal();
  /**
   * <code>bytes bytes_val = 5;</code>
   * @return The bytesVal.
   */
  com.google.protobuf.ByteString getBytesVal();

  /**
   * <code>double float64_val = 6;</code>
   * @return Whether the float64Val field is set.
   */
  boolean hasFloat64Val();
  /**
   * <code>double float64_val = 6;</code>
   * @return The float64Val.
   */
  double getFloat64Val();

  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 7;</code>
   * @return Whether the timestampVal field is set.
   */
  boolean hasTimestampVal();
  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 7;</code>
   * @return The timestampVal.
   */
  com.google.protobuf.Timestamp getTimestampVal();
  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampValOrBuilder();

  public com.pancakedb.idl.FieldValue.ValueCase getValueCase();
}
