// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface ListSegmentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.ListSegmentsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.dml.Segment segments = 1;</code>
   */
  java.util.List<com.pancakedb.idl.Segment> 
      getSegmentsList();
  /**
   * <code>repeated .protos.dml.Segment segments = 1;</code>
   */
  com.pancakedb.idl.Segment getSegments(int index);
  /**
   * <code>repeated .protos.dml.Segment segments = 1;</code>
   */
  int getSegmentsCount();
  /**
   * <code>repeated .protos.dml.Segment segments = 1;</code>
   */
  java.util.List<? extends com.pancakedb.idl.SegmentOrBuilder> 
      getSegmentsOrBuilderList();
  /**
   * <code>repeated .protos.dml.Segment segments = 1;</code>
   */
  com.pancakedb.idl.SegmentOrBuilder getSegmentsOrBuilder(
      int index);
}
