// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface PartitionFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.PartitionField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string string_val = 2;</code>
   * @return Whether the stringVal field is set.
   */
  boolean hasStringVal();
  /**
   * <code>string string_val = 2;</code>
   * @return The stringVal.
   */
  java.lang.String getStringVal();
  /**
   * <code>string string_val = 2;</code>
   * @return The bytes for stringVal.
   */
  com.google.protobuf.ByteString
      getStringValBytes();

  /**
   * <code>int64 int64_val = 3;</code>
   * @return Whether the int64Val field is set.
   */
  boolean hasInt64Val();
  /**
   * <code>int64 int64_val = 3;</code>
   * @return The int64Val.
   */
  long getInt64Val();

  /**
   * <code>bool bool_val = 4;</code>
   * @return Whether the boolVal field is set.
   */
  boolean hasBoolVal();
  /**
   * <code>bool bool_val = 4;</code>
   * @return The boolVal.
   */
  boolean getBoolVal();

  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
   * @return Whether the timestampVal field is set.
   */
  boolean hasTimestampVal();
  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
   * @return The timestampVal.
   */
  com.google.protobuf.Timestamp getTimestampVal();
  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampValOrBuilder();

  public com.pancakedb.idl.PartitionField.ValueCase getValueCase();
}
