// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partition_dtype.proto

package com.pancakedb.idl;

public final class PartitionDtype {
  private PartitionDtype() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025partition_dtype.proto\022\026protos.partitio" +
      "n_dtype*J\n\021PartitionDataType\022\n\n\006STRING\020\000" +
      "\022\010\n\004BOOL\020\001\022\t\n\005INT64\020\002\022\024\n\020TIMESTAMP_MINUT" +
      "E\020\003B\025\n\021com.pancakedb.idlP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
