// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface PartitionFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.PartitionFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.dml.PartitionField equal_to = 1;</code>
   * @return Whether the equalTo field is set.
   */
  boolean hasEqualTo();
  /**
   * <code>.protos.dml.PartitionField equal_to = 1;</code>
   * @return The equalTo.
   */
  com.pancakedb.idl.PartitionField getEqualTo();
  /**
   * <code>.protos.dml.PartitionField equal_to = 1;</code>
   */
  com.pancakedb.idl.PartitionFieldOrBuilder getEqualToOrBuilder();

  /**
   * <code>.protos.dml.PartitionField less_or_eq_to = 2;</code>
   * @return Whether the lessOrEqTo field is set.
   */
  boolean hasLessOrEqTo();
  /**
   * <code>.protos.dml.PartitionField less_or_eq_to = 2;</code>
   * @return The lessOrEqTo.
   */
  com.pancakedb.idl.PartitionField getLessOrEqTo();
  /**
   * <code>.protos.dml.PartitionField less_or_eq_to = 2;</code>
   */
  com.pancakedb.idl.PartitionFieldOrBuilder getLessOrEqToOrBuilder();

  /**
   * <code>.protos.dml.PartitionField less_than = 3;</code>
   * @return Whether the lessThan field is set.
   */
  boolean hasLessThan();
  /**
   * <code>.protos.dml.PartitionField less_than = 3;</code>
   * @return The lessThan.
   */
  com.pancakedb.idl.PartitionField getLessThan();
  /**
   * <code>.protos.dml.PartitionField less_than = 3;</code>
   */
  com.pancakedb.idl.PartitionFieldOrBuilder getLessThanOrBuilder();

  /**
   * <code>.protos.dml.PartitionField greater_or_eq_to = 4;</code>
   * @return Whether the greaterOrEqTo field is set.
   */
  boolean hasGreaterOrEqTo();
  /**
   * <code>.protos.dml.PartitionField greater_or_eq_to = 4;</code>
   * @return The greaterOrEqTo.
   */
  com.pancakedb.idl.PartitionField getGreaterOrEqTo();
  /**
   * <code>.protos.dml.PartitionField greater_or_eq_to = 4;</code>
   */
  com.pancakedb.idl.PartitionFieldOrBuilder getGreaterOrEqToOrBuilder();

  /**
   * <code>.protos.dml.PartitionField greater_than = 5;</code>
   * @return Whether the greaterThan field is set.
   */
  boolean hasGreaterThan();
  /**
   * <code>.protos.dml.PartitionField greater_than = 5;</code>
   * @return The greaterThan.
   */
  com.pancakedb.idl.PartitionField getGreaterThan();
  /**
   * <code>.protos.dml.PartitionField greater_than = 5;</code>
   */
  com.pancakedb.idl.PartitionFieldOrBuilder getGreaterThanOrBuilder();

  public com.pancakedb.idl.PartitionFilter.ValueCase getValueCase();
}
