// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface PartitionFieldComparisonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.PartitionFieldComparison)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.protos.dml.PartitionFieldComparison.Operator operator = 2;</code>
   * @return The enum numeric value on the wire for operator.
   */
  int getOperatorValue();
  /**
   * <code>.protos.dml.PartitionFieldComparison.Operator operator = 2;</code>
   * @return The operator.
   */
  com.pancakedb.idl.PartitionFieldComparison.Operator getOperator();

  /**
   * <code>.protos.dml.PartitionFieldValue value = 3;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.protos.dml.PartitionFieldValue value = 3;</code>
   * @return The value.
   */
  com.pancakedb.idl.PartitionFieldValue getValue();
  /**
   * <code>.protos.dml.PartitionFieldValue value = 3;</code>
   */
  com.pancakedb.idl.PartitionFieldValueOrBuilder getValueOrBuilder();
}
