// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface PartitionFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.PartitionFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.dml.PartitionFieldComparison comparison = 1;</code>
   * @return Whether the comparison field is set.
   */
  boolean hasComparison();
  /**
   * <code>.protos.dml.PartitionFieldComparison comparison = 1;</code>
   * @return The comparison.
   */
  com.pancakedb.idl.PartitionFieldComparison getComparison();
  /**
   * <code>.protos.dml.PartitionFieldComparison comparison = 1;</code>
   */
  com.pancakedb.idl.PartitionFieldComparisonOrBuilder getComparisonOrBuilder();

  public com.pancakedb.idl.PartitionFilter.ValueCase getValueCase();
}
