// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

/**
 * Protobuf type {@code protos.dml.PartitionField}
 */
public final class PartitionField extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.dml.PartitionField)
    PartitionFieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PartitionField.newBuilder() to construct.
  private PartitionField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PartitionField() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PartitionField();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PartitionField(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            valueCase_ = 2;
            value_ = s;
            break;
          }
          case 24: {
            valueCase_ = 3;
            value_ = input.readInt64();
            break;
          }
          case 32: {
            valueCase_ = 4;
            value_ = input.readBool();
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (valueCase_ == 5) {
              subBuilder = ((com.google.protobuf.Timestamp) value_).toBuilder();
            }
            value_ =
                input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Timestamp) value_);
              value_ = subBuilder.buildPartial();
            }
            valueCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pancakedb.idl.Dml.internal_static_protos_dml_PartitionField_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pancakedb.idl.Dml.internal_static_protos_dml_PartitionField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pancakedb.idl.PartitionField.class, com.pancakedb.idl.PartitionField.Builder.class);
  }

  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STRING_VAL(2),
    INT64_VAL(3),
    BOOL_VAL(4),
    TIMESTAMP_VAL(5),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 2: return STRING_VAL;
        case 3: return INT64_VAL;
        case 4: return BOOL_VAL;
        case 5: return TIMESTAMP_VAL;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRING_VAL_FIELD_NUMBER = 2;
  /**
   * <code>string string_val = 2;</code>
   * @return Whether the stringVal field is set.
   */
  public boolean hasStringVal() {
    return valueCase_ == 2;
  }
  /**
   * <code>string string_val = 2;</code>
   * @return The stringVal.
   */
  public java.lang.String getStringVal() {
    java.lang.Object ref = "";
    if (valueCase_ == 2) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valueCase_ == 2) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string string_val = 2;</code>
   * @return The bytes for stringVal.
   */
  public com.google.protobuf.ByteString
      getStringValBytes() {
    java.lang.Object ref = "";
    if (valueCase_ == 2) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valueCase_ == 2) {
        value_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INT64_VAL_FIELD_NUMBER = 3;
  /**
   * <code>int64 int64_val = 3;</code>
   * @return Whether the int64Val field is set.
   */
  @java.lang.Override
  public boolean hasInt64Val() {
    return valueCase_ == 3;
  }
  /**
   * <code>int64 int64_val = 3;</code>
   * @return The int64Val.
   */
  @java.lang.Override
  public long getInt64Val() {
    if (valueCase_ == 3) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }

  public static final int BOOL_VAL_FIELD_NUMBER = 4;
  /**
   * <code>bool bool_val = 4;</code>
   * @return Whether the boolVal field is set.
   */
  @java.lang.Override
  public boolean hasBoolVal() {
    return valueCase_ == 4;
  }
  /**
   * <code>bool bool_val = 4;</code>
   * @return The boolVal.
   */
  @java.lang.Override
  public boolean getBoolVal() {
    if (valueCase_ == 4) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }

  public static final int TIMESTAMP_VAL_FIELD_NUMBER = 5;
  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
   * @return Whether the timestampVal field is set.
   */
  @java.lang.Override
  public boolean hasTimestampVal() {
    return valueCase_ == 5;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
   * @return The timestampVal.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestampVal() {
    if (valueCase_ == 5) {
       return (com.google.protobuf.Timestamp) value_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampValOrBuilder() {
    if (valueCase_ == 5) {
       return (com.google.protobuf.Timestamp) value_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (valueCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
    }
    if (valueCase_ == 3) {
      output.writeInt64(
          3, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 4) {
      output.writeBool(
          4, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 5) {
      output.writeMessage(5, (com.google.protobuf.Timestamp) value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            3, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            4, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.google.protobuf.Timestamp) value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pancakedb.idl.PartitionField)) {
      return super.equals(obj);
    }
    com.pancakedb.idl.PartitionField other = (com.pancakedb.idl.PartitionField) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 2:
        if (!getStringVal()
            .equals(other.getStringVal())) return false;
        break;
      case 3:
        if (getInt64Val()
            != other.getInt64Val()) return false;
        break;
      case 4:
        if (getBoolVal()
            != other.getBoolVal()) return false;
        break;
      case 5:
        if (!getTimestampVal()
            .equals(other.getTimestampVal())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    switch (valueCase_) {
      case 2:
        hash = (37 * hash) + STRING_VAL_FIELD_NUMBER;
        hash = (53 * hash) + getStringVal().hashCode();
        break;
      case 3:
        hash = (37 * hash) + INT64_VAL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInt64Val());
        break;
      case 4:
        hash = (37 * hash) + BOOL_VAL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolVal());
        break;
      case 5:
        hash = (37 * hash) + TIMESTAMP_VAL_FIELD_NUMBER;
        hash = (53 * hash) + getTimestampVal().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pancakedb.idl.PartitionField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.PartitionField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.PartitionField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.PartitionField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pancakedb.idl.PartitionField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.dml.PartitionField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.dml.PartitionField)
      com.pancakedb.idl.PartitionFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pancakedb.idl.Dml.internal_static_protos_dml_PartitionField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pancakedb.idl.Dml.internal_static_protos_dml_PartitionField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pancakedb.idl.PartitionField.class, com.pancakedb.idl.PartitionField.Builder.class);
    }

    // Construct using com.pancakedb.idl.PartitionField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pancakedb.idl.Dml.internal_static_protos_dml_PartitionField_descriptor;
    }

    @java.lang.Override
    public com.pancakedb.idl.PartitionField getDefaultInstanceForType() {
      return com.pancakedb.idl.PartitionField.getDefaultInstance();
    }

    @java.lang.Override
    public com.pancakedb.idl.PartitionField build() {
      com.pancakedb.idl.PartitionField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pancakedb.idl.PartitionField buildPartial() {
      com.pancakedb.idl.PartitionField result = new com.pancakedb.idl.PartitionField(this);
      result.name_ = name_;
      if (valueCase_ == 2) {
        result.value_ = value_;
      }
      if (valueCase_ == 3) {
        result.value_ = value_;
      }
      if (valueCase_ == 4) {
        result.value_ = value_;
      }
      if (valueCase_ == 5) {
        if (timestampValBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = timestampValBuilder_.build();
        }
      }
      result.valueCase_ = valueCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pancakedb.idl.PartitionField) {
        return mergeFrom((com.pancakedb.idl.PartitionField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pancakedb.idl.PartitionField other) {
      if (other == com.pancakedb.idl.PartitionField.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      switch (other.getValueCase()) {
        case STRING_VAL: {
          valueCase_ = 2;
          value_ = other.value_;
          onChanged();
          break;
        }
        case INT64_VAL: {
          setInt64Val(other.getInt64Val());
          break;
        }
        case BOOL_VAL: {
          setBoolVal(other.getBoolVal());
          break;
        }
        case TIMESTAMP_VAL: {
          mergeTimestampVal(other.getTimestampVal());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pancakedb.idl.PartitionField parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pancakedb.idl.PartitionField) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string string_val = 2;</code>
     * @return Whether the stringVal field is set.
     */
    @java.lang.Override
    public boolean hasStringVal() {
      return valueCase_ == 2;
    }
    /**
     * <code>string string_val = 2;</code>
     * @return The stringVal.
     */
    @java.lang.Override
    public java.lang.String getStringVal() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 2) {
          value_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_val = 2;</code>
     * @return The bytes for stringVal.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 2) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_val = 2;</code>
     * @param value The stringVal to set.
     * @return This builder for chaining.
     */
    public Builder setStringVal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string_val = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringVal() {
      if (valueCase_ == 2) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string string_val = 2;</code>
     * @param value The bytes for stringVal to set.
     * @return This builder for chaining.
     */
    public Builder setStringValBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int64 int64_val = 3;</code>
     * @return Whether the int64Val field is set.
     */
    public boolean hasInt64Val() {
      return valueCase_ == 3;
    }
    /**
     * <code>int64 int64_val = 3;</code>
     * @return The int64Val.
     */
    public long getInt64Val() {
      if (valueCase_ == 3) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }
    /**
     * <code>int64 int64_val = 3;</code>
     * @param value The int64Val to set.
     * @return This builder for chaining.
     */
    public Builder setInt64Val(long value) {
      valueCase_ = 3;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 int64_val = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64Val() {
      if (valueCase_ == 3) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool bool_val = 4;</code>
     * @return Whether the boolVal field is set.
     */
    public boolean hasBoolVal() {
      return valueCase_ == 4;
    }
    /**
     * <code>bool bool_val = 4;</code>
     * @return The boolVal.
     */
    public boolean getBoolVal() {
      if (valueCase_ == 4) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }
    /**
     * <code>bool bool_val = 4;</code>
     * @param value The boolVal to set.
     * @return This builder for chaining.
     */
    public Builder setBoolVal(boolean value) {
      valueCase_ = 4;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool_val = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolVal() {
      if (valueCase_ == 4) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampValBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     * @return Whether the timestampVal field is set.
     */
    @java.lang.Override
    public boolean hasTimestampVal() {
      return valueCase_ == 5;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     * @return The timestampVal.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestampVal() {
      if (timestampValBuilder_ == null) {
        if (valueCase_ == 5) {
          return (com.google.protobuf.Timestamp) value_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      } else {
        if (valueCase_ == 5) {
          return timestampValBuilder_.getMessage();
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     */
    public Builder setTimestampVal(com.google.protobuf.Timestamp value) {
      if (timestampValBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        timestampValBuilder_.setMessage(value);
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     */
    public Builder setTimestampVal(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampValBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        timestampValBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     */
    public Builder mergeTimestampVal(com.google.protobuf.Timestamp value) {
      if (timestampValBuilder_ == null) {
        if (valueCase_ == 5 &&
            value_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          value_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 5) {
          timestampValBuilder_.mergeFrom(value);
        }
        timestampValBuilder_.setMessage(value);
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     */
    public Builder clearTimestampVal() {
      if (timestampValBuilder_ == null) {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
        }
        timestampValBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampValBuilder() {
      return getTimestampValFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampValOrBuilder() {
      if ((valueCase_ == 5) && (timestampValBuilder_ != null)) {
        return timestampValBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 5) {
          return (com.google.protobuf.Timestamp) value_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp_val = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampValFieldBuilder() {
      if (timestampValBuilder_ == null) {
        if (!(valueCase_ == 5)) {
          value_ = com.google.protobuf.Timestamp.getDefaultInstance();
        }
        timestampValBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                (com.google.protobuf.Timestamp) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 5;
      onChanged();;
      return timestampValBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.dml.PartitionField)
  }

  // @@protoc_insertion_point(class_scope:protos.dml.PartitionField)
  private static final com.pancakedb.idl.PartitionField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pancakedb.idl.PartitionField();
  }

  public static com.pancakedb.idl.PartitionField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartitionField>
      PARSER = new com.google.protobuf.AbstractParser<PartitionField>() {
    @java.lang.Override
    public PartitionField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PartitionField(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PartitionField> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartitionField> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pancakedb.idl.PartitionField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

