// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.pancakedb.idl;

public interface PartitionMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.schema.PartitionMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.protos.partition_dtype.PartitionDataType dtype = 2;</code>
   * @return The enum numeric value on the wire for dtype.
   */
  int getDtypeValue();
  /**
   * <code>.protos.partition_dtype.PartitionDataType dtype = 2;</code>
   * @return The dtype.
   */
  com.pancakedb.idl.PartitionDataType getDtype();
}
