// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface ReadSegmentColumnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.ReadSegmentColumnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table_name = 1;</code>
   * @return The tableName.
   */
  java.lang.String getTableName();
  /**
   * <code>string table_name = 1;</code>
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>map&lt;string, .protos.dml.PartitionFieldValue&gt; partition = 2;</code>
   */
  int getPartitionCount();
  /**
   * <code>map&lt;string, .protos.dml.PartitionFieldValue&gt; partition = 2;</code>
   */
  boolean containsPartition(
      java.lang.String key);
  /**
   * Use {@link #getPartitionMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.pancakedb.idl.PartitionFieldValue>
  getPartition();
  /**
   * <code>map&lt;string, .protos.dml.PartitionFieldValue&gt; partition = 2;</code>
   */
  java.util.Map<java.lang.String, com.pancakedb.idl.PartitionFieldValue>
  getPartitionMap();
  /**
   * <code>map&lt;string, .protos.dml.PartitionFieldValue&gt; partition = 2;</code>
   */

  com.pancakedb.idl.PartitionFieldValue getPartitionOrDefault(
      java.lang.String key,
      com.pancakedb.idl.PartitionFieldValue defaultValue);
  /**
   * <code>map&lt;string, .protos.dml.PartitionFieldValue&gt; partition = 2;</code>
   */

  com.pancakedb.idl.PartitionFieldValue getPartitionOrThrow(
      java.lang.String key);

  /**
   * <code>string segment_id = 3;</code>
   * @return The segmentId.
   */
  java.lang.String getSegmentId();
  /**
   * <code>string segment_id = 3;</code>
   * @return The bytes for segmentId.
   */
  com.google.protobuf.ByteString
      getSegmentIdBytes();

  /**
   * <code>string column_name = 4;</code>
   * @return The columnName.
   */
  java.lang.String getColumnName();
  /**
   * <code>string column_name = 4;</code>
   * @return The bytes for columnName.
   */
  com.google.protobuf.ByteString
      getColumnNameBytes();

  /**
   * <code>string correlation_id = 5;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlation_id = 5;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <code>string continuation_token = 6;</code>
   * @return The continuationToken.
   */
  java.lang.String getContinuationToken();
  /**
   * <code>string continuation_token = 6;</code>
   * @return The bytes for continuationToken.
   */
  com.google.protobuf.ByteString
      getContinuationTokenBytes();
}
