// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface ReadSegmentColumnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.ReadSegmentColumnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table_name = 1;</code>
   * @return The tableName.
   */
  java.lang.String getTableName();
  /**
   * <code>string table_name = 1;</code>
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  java.util.List<com.pancakedb.idl.PartitionField> 
      getPartitionList();
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  com.pancakedb.idl.PartitionField getPartition(int index);
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  int getPartitionCount();
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  java.util.List<? extends com.pancakedb.idl.PartitionFieldOrBuilder> 
      getPartitionOrBuilderList();
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  com.pancakedb.idl.PartitionFieldOrBuilder getPartitionOrBuilder(
      int index);

  /**
   * <code>string segment_id = 3;</code>
   * @return The segmentId.
   */
  java.lang.String getSegmentId();
  /**
   * <code>string segment_id = 3;</code>
   * @return The bytes for segmentId.
   */
  com.google.protobuf.ByteString
      getSegmentIdBytes();

  /**
   * <code>string column_name = 4;</code>
   * @return The columnName.
   */
  java.lang.String getColumnName();
  /**
   * <code>string column_name = 4;</code>
   * @return The bytes for columnName.
   */
  com.google.protobuf.ByteString
      getColumnNameBytes();

  /**
   * <code>string continuation_token = 5;</code>
   * @return The continuationToken.
   */
  java.lang.String getContinuationToken();
  /**
   * <code>string continuation_token = 5;</code>
   * @return The bytes for continuationToken.
   */
  com.google.protobuf.ByteString
      getContinuationTokenBytes();
}
