// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.dml.Field fields = 1;</code>
   */
  java.util.List<com.pancakedb.idl.Field> 
      getFieldsList();
  /**
   * <code>repeated .protos.dml.Field fields = 1;</code>
   */
  com.pancakedb.idl.Field getFields(int index);
  /**
   * <code>repeated .protos.dml.Field fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .protos.dml.Field fields = 1;</code>
   */
  java.util.List<? extends com.pancakedb.idl.FieldOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .protos.dml.Field fields = 1;</code>
   */
  com.pancakedb.idl.FieldOrBuilder getFieldsOrBuilder(
      int index);
}
