// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.pancakedb.idl;

/**
 * Protobuf type {@code protos.schema.Schema}
 */
public final class Schema extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.schema.Schema)
    SchemaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Schema.newBuilder() to construct.
  private Schema(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Schema() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Schema();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Schema(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              partitioning_ = com.google.protobuf.MapField.newMapField(
                  PartitioningDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.pancakedb.idl.PartitionMeta>
            partitioning__ = input.readMessage(
                PartitioningDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            partitioning_.getMutableMap().put(
                partitioning__.getKey(), partitioning__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              columns_ = com.google.protobuf.MapField.newMapField(
                  ColumnsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.pancakedb.idl.ColumnMeta>
            columns__ = input.readMessage(
                ColumnsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            columns_.getMutableMap().put(
                columns__.getKey(), columns__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pancakedb.idl.SchemaOuterClass.internal_static_protos_schema_Schema_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetPartitioning();
      case 2:
        return internalGetColumns();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pancakedb.idl.SchemaOuterClass.internal_static_protos_schema_Schema_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pancakedb.idl.Schema.class, com.pancakedb.idl.Schema.Builder.class);
  }

  public static final int PARTITIONING_FIELD_NUMBER = 1;
  private static final class PartitioningDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.pancakedb.idl.PartitionMeta> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.pancakedb.idl.PartitionMeta>newDefaultInstance(
                com.pancakedb.idl.SchemaOuterClass.internal_static_protos_schema_Schema_PartitioningEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.pancakedb.idl.PartitionMeta.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.pancakedb.idl.PartitionMeta> partitioning_;
  private com.google.protobuf.MapField<java.lang.String, com.pancakedb.idl.PartitionMeta>
  internalGetPartitioning() {
    if (partitioning_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PartitioningDefaultEntryHolder.defaultEntry);
    }
    return partitioning_;
  }

  public int getPartitioningCount() {
    return internalGetPartitioning().getMap().size();
  }
  /**
   * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
   */

  @java.lang.Override
  public boolean containsPartitioning(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetPartitioning().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPartitioningMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> getPartitioning() {
    return getPartitioningMap();
  }
  /**
   * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> getPartitioningMap() {
    return internalGetPartitioning().getMap();
  }
  /**
   * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
   */
  @java.lang.Override

  public com.pancakedb.idl.PartitionMeta getPartitioningOrDefault(
      java.lang.String key,
      com.pancakedb.idl.PartitionMeta defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> map =
        internalGetPartitioning().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
   */
  @java.lang.Override

  public com.pancakedb.idl.PartitionMeta getPartitioningOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> map =
        internalGetPartitioning().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int COLUMNS_FIELD_NUMBER = 2;
  private static final class ColumnsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.pancakedb.idl.ColumnMeta> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.pancakedb.idl.ColumnMeta>newDefaultInstance(
                com.pancakedb.idl.SchemaOuterClass.internal_static_protos_schema_Schema_ColumnsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.pancakedb.idl.ColumnMeta.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.pancakedb.idl.ColumnMeta> columns_;
  private com.google.protobuf.MapField<java.lang.String, com.pancakedb.idl.ColumnMeta>
  internalGetColumns() {
    if (columns_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ColumnsDefaultEntryHolder.defaultEntry);
    }
    return columns_;
  }

  public int getColumnsCount() {
    return internalGetColumns().getMap().size();
  }
  /**
   * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
   */

  @java.lang.Override
  public boolean containsColumns(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetColumns().getMap().containsKey(key);
  }
  /**
   * Use {@link #getColumnsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> getColumns() {
    return getColumnsMap();
  }
  /**
   * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> getColumnsMap() {
    return internalGetColumns().getMap();
  }
  /**
   * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
   */
  @java.lang.Override

  public com.pancakedb.idl.ColumnMeta getColumnsOrDefault(
      java.lang.String key,
      com.pancakedb.idl.ColumnMeta defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> map =
        internalGetColumns().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
   */
  @java.lang.Override

  public com.pancakedb.idl.ColumnMeta getColumnsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> map =
        internalGetColumns().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetPartitioning(),
        PartitioningDefaultEntryHolder.defaultEntry,
        1);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetColumns(),
        ColumnsDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.pancakedb.idl.PartitionMeta> entry
         : internalGetPartitioning().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.pancakedb.idl.PartitionMeta>
      partitioning__ = PartitioningDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, partitioning__);
    }
    for (java.util.Map.Entry<java.lang.String, com.pancakedb.idl.ColumnMeta> entry
         : internalGetColumns().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.pancakedb.idl.ColumnMeta>
      columns__ = ColumnsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, columns__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pancakedb.idl.Schema)) {
      return super.equals(obj);
    }
    com.pancakedb.idl.Schema other = (com.pancakedb.idl.Schema) obj;

    if (!internalGetPartitioning().equals(
        other.internalGetPartitioning())) return false;
    if (!internalGetColumns().equals(
        other.internalGetColumns())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetPartitioning().getMap().isEmpty()) {
      hash = (37 * hash) + PARTITIONING_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPartitioning().hashCode();
    }
    if (!internalGetColumns().getMap().isEmpty()) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetColumns().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pancakedb.idl.Schema parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.Schema parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.Schema parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.Schema parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.Schema parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.Schema parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.Schema parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.Schema parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.Schema parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.Schema parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.Schema parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.Schema parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pancakedb.idl.Schema prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.schema.Schema}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.schema.Schema)
      com.pancakedb.idl.SchemaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pancakedb.idl.SchemaOuterClass.internal_static_protos_schema_Schema_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetPartitioning();
        case 2:
          return internalGetColumns();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutablePartitioning();
        case 2:
          return internalGetMutableColumns();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pancakedb.idl.SchemaOuterClass.internal_static_protos_schema_Schema_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pancakedb.idl.Schema.class, com.pancakedb.idl.Schema.Builder.class);
    }

    // Construct using com.pancakedb.idl.Schema.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutablePartitioning().clear();
      internalGetMutableColumns().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pancakedb.idl.SchemaOuterClass.internal_static_protos_schema_Schema_descriptor;
    }

    @java.lang.Override
    public com.pancakedb.idl.Schema getDefaultInstanceForType() {
      return com.pancakedb.idl.Schema.getDefaultInstance();
    }

    @java.lang.Override
    public com.pancakedb.idl.Schema build() {
      com.pancakedb.idl.Schema result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pancakedb.idl.Schema buildPartial() {
      com.pancakedb.idl.Schema result = new com.pancakedb.idl.Schema(this);
      int from_bitField0_ = bitField0_;
      result.partitioning_ = internalGetPartitioning();
      result.partitioning_.makeImmutable();
      result.columns_ = internalGetColumns();
      result.columns_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pancakedb.idl.Schema) {
        return mergeFrom((com.pancakedb.idl.Schema)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pancakedb.idl.Schema other) {
      if (other == com.pancakedb.idl.Schema.getDefaultInstance()) return this;
      internalGetMutablePartitioning().mergeFrom(
          other.internalGetPartitioning());
      internalGetMutableColumns().mergeFrom(
          other.internalGetColumns());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pancakedb.idl.Schema parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pancakedb.idl.Schema) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.pancakedb.idl.PartitionMeta> partitioning_;
    private com.google.protobuf.MapField<java.lang.String, com.pancakedb.idl.PartitionMeta>
    internalGetPartitioning() {
      if (partitioning_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PartitioningDefaultEntryHolder.defaultEntry);
      }
      return partitioning_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.pancakedb.idl.PartitionMeta>
    internalGetMutablePartitioning() {
      onChanged();;
      if (partitioning_ == null) {
        partitioning_ = com.google.protobuf.MapField.newMapField(
            PartitioningDefaultEntryHolder.defaultEntry);
      }
      if (!partitioning_.isMutable()) {
        partitioning_ = partitioning_.copy();
      }
      return partitioning_;
    }

    public int getPartitioningCount() {
      return internalGetPartitioning().getMap().size();
    }
    /**
     * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
     */

    @java.lang.Override
    public boolean containsPartitioning(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPartitioning().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPartitioningMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> getPartitioning() {
      return getPartitioningMap();
    }
    /**
     * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> getPartitioningMap() {
      return internalGetPartitioning().getMap();
    }
    /**
     * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
     */
    @java.lang.Override

    public com.pancakedb.idl.PartitionMeta getPartitioningOrDefault(
        java.lang.String key,
        com.pancakedb.idl.PartitionMeta defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> map =
          internalGetPartitioning().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
     */
    @java.lang.Override

    public com.pancakedb.idl.PartitionMeta getPartitioningOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> map =
          internalGetPartitioning().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPartitioning() {
      internalGetMutablePartitioning().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
     */

    public Builder removePartitioning(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePartitioning().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta>
    getMutablePartitioning() {
      return internalGetMutablePartitioning().getMutableMap();
    }
    /**
     * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
     */
    public Builder putPartitioning(
        java.lang.String key,
        com.pancakedb.idl.PartitionMeta value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePartitioning().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .protos.schema.PartitionMeta&gt; partitioning = 1;</code>
     */

    public Builder putAllPartitioning(
        java.util.Map<java.lang.String, com.pancakedb.idl.PartitionMeta> values) {
      internalGetMutablePartitioning().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.pancakedb.idl.ColumnMeta> columns_;
    private com.google.protobuf.MapField<java.lang.String, com.pancakedb.idl.ColumnMeta>
    internalGetColumns() {
      if (columns_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ColumnsDefaultEntryHolder.defaultEntry);
      }
      return columns_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.pancakedb.idl.ColumnMeta>
    internalGetMutableColumns() {
      onChanged();;
      if (columns_ == null) {
        columns_ = com.google.protobuf.MapField.newMapField(
            ColumnsDefaultEntryHolder.defaultEntry);
      }
      if (!columns_.isMutable()) {
        columns_ = columns_.copy();
      }
      return columns_;
    }

    public int getColumnsCount() {
      return internalGetColumns().getMap().size();
    }
    /**
     * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
     */

    @java.lang.Override
    public boolean containsColumns(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetColumns().getMap().containsKey(key);
    }
    /**
     * Use {@link #getColumnsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> getColumns() {
      return getColumnsMap();
    }
    /**
     * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> getColumnsMap() {
      return internalGetColumns().getMap();
    }
    /**
     * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
     */
    @java.lang.Override

    public com.pancakedb.idl.ColumnMeta getColumnsOrDefault(
        java.lang.String key,
        com.pancakedb.idl.ColumnMeta defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> map =
          internalGetColumns().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
     */
    @java.lang.Override

    public com.pancakedb.idl.ColumnMeta getColumnsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> map =
          internalGetColumns().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearColumns() {
      internalGetMutableColumns().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
     */

    public Builder removeColumns(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableColumns().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta>
    getMutableColumns() {
      return internalGetMutableColumns().getMutableMap();
    }
    /**
     * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
     */
    public Builder putColumns(
        java.lang.String key,
        com.pancakedb.idl.ColumnMeta value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableColumns().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .protos.schema.ColumnMeta&gt; columns = 2;</code>
     */

    public Builder putAllColumns(
        java.util.Map<java.lang.String, com.pancakedb.idl.ColumnMeta> values) {
      internalGetMutableColumns().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.schema.Schema)
  }

  // @@protoc_insertion_point(class_scope:protos.schema.Schema)
  private static final com.pancakedb.idl.Schema DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pancakedb.idl.Schema();
  }

  public static com.pancakedb.idl.Schema getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Schema>
      PARSER = new com.google.protobuf.AbstractParser<Schema>() {
    @java.lang.Override
    public Schema parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Schema(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Schema> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Schema> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pancakedb.idl.Schema getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

