// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.pancakedb.idl;

public interface SchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.schema.Schema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.schema.PartitionMeta partitioning = 1;</code>
   */
  java.util.List<com.pancakedb.idl.PartitionMeta> 
      getPartitioningList();
  /**
   * <code>repeated .protos.schema.PartitionMeta partitioning = 1;</code>
   */
  com.pancakedb.idl.PartitionMeta getPartitioning(int index);
  /**
   * <code>repeated .protos.schema.PartitionMeta partitioning = 1;</code>
   */
  int getPartitioningCount();
  /**
   * <code>repeated .protos.schema.PartitionMeta partitioning = 1;</code>
   */
  java.util.List<? extends com.pancakedb.idl.PartitionMetaOrBuilder> 
      getPartitioningOrBuilderList();
  /**
   * <code>repeated .protos.schema.PartitionMeta partitioning = 1;</code>
   */
  com.pancakedb.idl.PartitionMetaOrBuilder getPartitioningOrBuilder(
      int index);

  /**
   * <code>repeated .protos.schema.ColumnMeta columns = 2;</code>
   */
  java.util.List<com.pancakedb.idl.ColumnMeta> 
      getColumnsList();
  /**
   * <code>repeated .protos.schema.ColumnMeta columns = 2;</code>
   */
  com.pancakedb.idl.ColumnMeta getColumns(int index);
  /**
   * <code>repeated .protos.schema.ColumnMeta columns = 2;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .protos.schema.ColumnMeta columns = 2;</code>
   */
  java.util.List<? extends com.pancakedb.idl.ColumnMetaOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .protos.schema.ColumnMeta columns = 2;</code>
   */
  com.pancakedb.idl.ColumnMetaOrBuilder getColumnsOrBuilder(
      int index);
}
