// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface SegmentMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.SegmentMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 row_count = 1;</code>
   * @return The rowCount.
   */
  int getRowCount();
}
