// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.pancakedb.idl;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\016protos.service\032\tddl.pro" +
      "to\032\tdml.proto2\203\004\n\tPancakeDb\022N\n\013CreateTab" +
      "le\022\036.protos.ddl.CreateTableRequest\032\037.pro" +
      "tos.ddl.CreateTableResponse\022H\n\tDropTable" +
      "\022\034.protos.ddl.DropTableRequest\032\035.protos." +
      "ddl.DropTableResponse\022H\n\tGetSchema\022\034.pro" +
      "tos.ddl.GetSchemaRequest\032\035.protos.ddl.Ge" +
      "tSchemaResponse\022]\n\020WriteToPartition\022#.pr" +
      "otos.dml.WriteToPartitionRequest\032$.proto" +
      "s.dml.WriteToPartitionResponse\022Q\n\014ListSe" +
      "gments\022\037.protos.dml.ListSegmentsRequest\032" +
      " .protos.dml.ListSegmentsResponse\022`\n\021Rea" +
      "dSegmentColumn\022$.protos.dml.ReadSegmentC" +
      "olumnRequest\032%.protos.dml.ReadSegmentCol" +
      "umnResponseB\025\n\021com.pancakedb.idlP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pancakedb.idl.Ddl.getDescriptor(),
          com.pancakedb.idl.Dml.getDescriptor(),
        });
    com.pancakedb.idl.Ddl.getDescriptor();
    com.pancakedb.idl.Dml.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
