// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

/**
 * <pre>
 *WRITING
 * </pre>
 *
 * Protobuf type {@code protos.dml.WriteToPartitionRequest}
 */
public final class WriteToPartitionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.dml.WriteToPartitionRequest)
    WriteToPartitionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WriteToPartitionRequest.newBuilder() to construct.
  private WriteToPartitionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WriteToPartitionRequest() {
    tableName_ = "";
    partition_ = java.util.Collections.emptyList();
    rows_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WriteToPartitionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WriteToPartitionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              partition_ = new java.util.ArrayList<com.pancakedb.idl.PartitionField>();
              mutable_bitField0_ |= 0x00000001;
            }
            partition_.add(
                input.readMessage(com.pancakedb.idl.PartitionField.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              rows_ = new java.util.ArrayList<com.pancakedb.idl.Row>();
              mutable_bitField0_ |= 0x00000002;
            }
            rows_.add(
                input.readMessage(com.pancakedb.idl.Row.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        partition_ = java.util.Collections.unmodifiableList(partition_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        rows_ = java.util.Collections.unmodifiableList(rows_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pancakedb.idl.Dml.internal_static_protos_dml_WriteToPartitionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pancakedb.idl.Dml.internal_static_protos_dml_WriteToPartitionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pancakedb.idl.WriteToPartitionRequest.class, com.pancakedb.idl.WriteToPartitionRequest.Builder.class);
  }

  public static final int TABLE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object tableName_;
  /**
   * <code>string table_name = 1;</code>
   * @return The tableName.
   */
  @java.lang.Override
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string table_name = 1;</code>
   * @return The bytes for tableName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITION_FIELD_NUMBER = 2;
  private java.util.List<com.pancakedb.idl.PartitionField> partition_;
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.pancakedb.idl.PartitionField> getPartitionList() {
    return partition_;
  }
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.pancakedb.idl.PartitionFieldOrBuilder> 
      getPartitionOrBuilderList() {
    return partition_;
  }
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  @java.lang.Override
  public int getPartitionCount() {
    return partition_.size();
  }
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  @java.lang.Override
  public com.pancakedb.idl.PartitionField getPartition(int index) {
    return partition_.get(index);
  }
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  @java.lang.Override
  public com.pancakedb.idl.PartitionFieldOrBuilder getPartitionOrBuilder(
      int index) {
    return partition_.get(index);
  }

  public static final int ROWS_FIELD_NUMBER = 3;
  private java.util.List<com.pancakedb.idl.Row> rows_;
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.pancakedb.idl.Row> getRowsList() {
    return rows_;
  }
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.pancakedb.idl.RowOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  @java.lang.Override
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  @java.lang.Override
  public com.pancakedb.idl.Row getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  @java.lang.Override
  public com.pancakedb.idl.RowOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableName_);
    }
    for (int i = 0; i < partition_.size(); i++) {
      output.writeMessage(2, partition_.get(i));
    }
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(3, rows_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableName_);
    }
    for (int i = 0; i < partition_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, partition_.get(i));
    }
    for (int i = 0; i < rows_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, rows_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pancakedb.idl.WriteToPartitionRequest)) {
      return super.equals(obj);
    }
    com.pancakedb.idl.WriteToPartitionRequest other = (com.pancakedb.idl.WriteToPartitionRequest) obj;

    if (!getTableName()
        .equals(other.getTableName())) return false;
    if (!getPartitionList()
        .equals(other.getPartitionList())) return false;
    if (!getRowsList()
        .equals(other.getRowsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    if (getPartitionCount() > 0) {
      hash = (37 * hash) + PARTITION_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionList().hashCode();
    }
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pancakedb.idl.WriteToPartitionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pancakedb.idl.WriteToPartitionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *WRITING
   * </pre>
   *
   * Protobuf type {@code protos.dml.WriteToPartitionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.dml.WriteToPartitionRequest)
      com.pancakedb.idl.WriteToPartitionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pancakedb.idl.Dml.internal_static_protos_dml_WriteToPartitionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pancakedb.idl.Dml.internal_static_protos_dml_WriteToPartitionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pancakedb.idl.WriteToPartitionRequest.class, com.pancakedb.idl.WriteToPartitionRequest.Builder.class);
    }

    // Construct using com.pancakedb.idl.WriteToPartitionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPartitionFieldBuilder();
        getRowsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tableName_ = "";

      if (partitionBuilder_ == null) {
        partition_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        partitionBuilder_.clear();
      }
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pancakedb.idl.Dml.internal_static_protos_dml_WriteToPartitionRequest_descriptor;
    }

    @java.lang.Override
    public com.pancakedb.idl.WriteToPartitionRequest getDefaultInstanceForType() {
      return com.pancakedb.idl.WriteToPartitionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.pancakedb.idl.WriteToPartitionRequest build() {
      com.pancakedb.idl.WriteToPartitionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pancakedb.idl.WriteToPartitionRequest buildPartial() {
      com.pancakedb.idl.WriteToPartitionRequest result = new com.pancakedb.idl.WriteToPartitionRequest(this);
      int from_bitField0_ = bitField0_;
      result.tableName_ = tableName_;
      if (partitionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          partition_ = java.util.Collections.unmodifiableList(partition_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.partition_ = partition_;
      } else {
        result.partition_ = partitionBuilder_.build();
      }
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pancakedb.idl.WriteToPartitionRequest) {
        return mergeFrom((com.pancakedb.idl.WriteToPartitionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pancakedb.idl.WriteToPartitionRequest other) {
      if (other == com.pancakedb.idl.WriteToPartitionRequest.getDefaultInstance()) return this;
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (partitionBuilder_ == null) {
        if (!other.partition_.isEmpty()) {
          if (partition_.isEmpty()) {
            partition_ = other.partition_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePartitionIsMutable();
            partition_.addAll(other.partition_);
          }
          onChanged();
        }
      } else {
        if (!other.partition_.isEmpty()) {
          if (partitionBuilder_.isEmpty()) {
            partitionBuilder_.dispose();
            partitionBuilder_ = null;
            partition_ = other.partition_;
            bitField0_ = (bitField0_ & ~0x00000001);
            partitionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartitionFieldBuilder() : null;
          } else {
            partitionBuilder_.addAllMessages(other.partition_);
          }
        }
      }
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pancakedb.idl.WriteToPartitionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pancakedb.idl.WriteToPartitionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object tableName_ = "";
    /**
     * <code>string table_name = 1;</code>
     * @return The tableName.
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string table_name = 1;</code>
     * @return The bytes for tableName.
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string table_name = 1;</code>
     * @param value The tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 1;</code>
     * @param value The bytes for tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.pancakedb.idl.PartitionField> partition_ =
      java.util.Collections.emptyList();
    private void ensurePartitionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        partition_ = new java.util.ArrayList<com.pancakedb.idl.PartitionField>(partition_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pancakedb.idl.PartitionField, com.pancakedb.idl.PartitionField.Builder, com.pancakedb.idl.PartitionFieldOrBuilder> partitionBuilder_;

    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public java.util.List<com.pancakedb.idl.PartitionField> getPartitionList() {
      if (partitionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(partition_);
      } else {
        return partitionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public int getPartitionCount() {
      if (partitionBuilder_ == null) {
        return partition_.size();
      } else {
        return partitionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public com.pancakedb.idl.PartitionField getPartition(int index) {
      if (partitionBuilder_ == null) {
        return partition_.get(index);
      } else {
        return partitionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder setPartition(
        int index, com.pancakedb.idl.PartitionField value) {
      if (partitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionIsMutable();
        partition_.set(index, value);
        onChanged();
      } else {
        partitionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder setPartition(
        int index, com.pancakedb.idl.PartitionField.Builder builderForValue) {
      if (partitionBuilder_ == null) {
        ensurePartitionIsMutable();
        partition_.set(index, builderForValue.build());
        onChanged();
      } else {
        partitionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder addPartition(com.pancakedb.idl.PartitionField value) {
      if (partitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionIsMutable();
        partition_.add(value);
        onChanged();
      } else {
        partitionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder addPartition(
        int index, com.pancakedb.idl.PartitionField value) {
      if (partitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionIsMutable();
        partition_.add(index, value);
        onChanged();
      } else {
        partitionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder addPartition(
        com.pancakedb.idl.PartitionField.Builder builderForValue) {
      if (partitionBuilder_ == null) {
        ensurePartitionIsMutable();
        partition_.add(builderForValue.build());
        onChanged();
      } else {
        partitionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder addPartition(
        int index, com.pancakedb.idl.PartitionField.Builder builderForValue) {
      if (partitionBuilder_ == null) {
        ensurePartitionIsMutable();
        partition_.add(index, builderForValue.build());
        onChanged();
      } else {
        partitionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder addAllPartition(
        java.lang.Iterable<? extends com.pancakedb.idl.PartitionField> values) {
      if (partitionBuilder_ == null) {
        ensurePartitionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, partition_);
        onChanged();
      } else {
        partitionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder clearPartition() {
      if (partitionBuilder_ == null) {
        partition_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        partitionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public Builder removePartition(int index) {
      if (partitionBuilder_ == null) {
        ensurePartitionIsMutable();
        partition_.remove(index);
        onChanged();
      } else {
        partitionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public com.pancakedb.idl.PartitionField.Builder getPartitionBuilder(
        int index) {
      return getPartitionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public com.pancakedb.idl.PartitionFieldOrBuilder getPartitionOrBuilder(
        int index) {
      if (partitionBuilder_ == null) {
        return partition_.get(index);  } else {
        return partitionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public java.util.List<? extends com.pancakedb.idl.PartitionFieldOrBuilder> 
         getPartitionOrBuilderList() {
      if (partitionBuilder_ != null) {
        return partitionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(partition_);
      }
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public com.pancakedb.idl.PartitionField.Builder addPartitionBuilder() {
      return getPartitionFieldBuilder().addBuilder(
          com.pancakedb.idl.PartitionField.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public com.pancakedb.idl.PartitionField.Builder addPartitionBuilder(
        int index) {
      return getPartitionFieldBuilder().addBuilder(
          index, com.pancakedb.idl.PartitionField.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.dml.PartitionField partition = 2;</code>
     */
    public java.util.List<com.pancakedb.idl.PartitionField.Builder> 
         getPartitionBuilderList() {
      return getPartitionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pancakedb.idl.PartitionField, com.pancakedb.idl.PartitionField.Builder, com.pancakedb.idl.PartitionFieldOrBuilder> 
        getPartitionFieldBuilder() {
      if (partitionBuilder_ == null) {
        partitionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.pancakedb.idl.PartitionField, com.pancakedb.idl.PartitionField.Builder, com.pancakedb.idl.PartitionFieldOrBuilder>(
                partition_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        partition_ = null;
      }
      return partitionBuilder_;
    }

    private java.util.List<com.pancakedb.idl.Row> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rows_ = new java.util.ArrayList<com.pancakedb.idl.Row>(rows_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pancakedb.idl.Row, com.pancakedb.idl.Row.Builder, com.pancakedb.idl.RowOrBuilder> rowsBuilder_;

    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public java.util.List<com.pancakedb.idl.Row> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public com.pancakedb.idl.Row getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder setRows(
        int index, com.pancakedb.idl.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder setRows(
        int index, com.pancakedb.idl.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder addRows(com.pancakedb.idl.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder addRows(
        int index, com.pancakedb.idl.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder addRows(
        com.pancakedb.idl.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder addRows(
        int index, com.pancakedb.idl.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends com.pancakedb.idl.Row> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public com.pancakedb.idl.Row.Builder getRowsBuilder(
        int index) {
      return getRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public com.pancakedb.idl.RowOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public java.util.List<? extends com.pancakedb.idl.RowOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public com.pancakedb.idl.Row.Builder addRowsBuilder() {
      return getRowsFieldBuilder().addBuilder(
          com.pancakedb.idl.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public com.pancakedb.idl.Row.Builder addRowsBuilder(
        int index) {
      return getRowsFieldBuilder().addBuilder(
          index, com.pancakedb.idl.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.dml.Row rows = 3;</code>
     */
    public java.util.List<com.pancakedb.idl.Row.Builder> 
         getRowsBuilderList() {
      return getRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pancakedb.idl.Row, com.pancakedb.idl.Row.Builder, com.pancakedb.idl.RowOrBuilder> 
        getRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.pancakedb.idl.Row, com.pancakedb.idl.Row.Builder, com.pancakedb.idl.RowOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.dml.WriteToPartitionRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.dml.WriteToPartitionRequest)
  private static final com.pancakedb.idl.WriteToPartitionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pancakedb.idl.WriteToPartitionRequest();
  }

  public static com.pancakedb.idl.WriteToPartitionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WriteToPartitionRequest>
      PARSER = new com.google.protobuf.AbstractParser<WriteToPartitionRequest>() {
    @java.lang.Override
    public WriteToPartitionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WriteToPartitionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WriteToPartitionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WriteToPartitionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pancakedb.idl.WriteToPartitionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

