// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dml.proto

package com.pancakedb.idl;

public interface WriteToPartitionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.dml.WriteToPartitionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table_name = 1;</code>
   * @return The tableName.
   */
  java.lang.String getTableName();
  /**
   * <code>string table_name = 1;</code>
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  java.util.List<com.pancakedb.idl.PartitionField> 
      getPartitionList();
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  com.pancakedb.idl.PartitionField getPartition(int index);
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  int getPartitionCount();
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  java.util.List<? extends com.pancakedb.idl.PartitionFieldOrBuilder> 
      getPartitionOrBuilderList();
  /**
   * <code>repeated .protos.dml.PartitionField partition = 2;</code>
   */
  com.pancakedb.idl.PartitionFieldOrBuilder getPartitionOrBuilder(
      int index);

  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  java.util.List<com.pancakedb.idl.Row> 
      getRowsList();
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  com.pancakedb.idl.Row getRows(int index);
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  java.util.List<? extends com.pancakedb.idl.RowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .protos.dml.Row rows = 3;</code>
   */
  com.pancakedb.idl.RowOrBuilder getRowsOrBuilder(
      int index);
}
