# note that we don't use a build script because it makes static analysis impossible

[package]
name = "pancake-db-idl"
version = "0.0.0-alpha.0"
edition = "2018"

authors = ["mwlon <m.w.loncaric@gmail.com>"]
description = "API specification for PancakeDB"
keywords = ["pancake", "idl", "protobuf"]
license = "Apache-2.0"
repository = "https://github.com/pancake-db/pancake-idl/"

[dependencies]
protobuf = "3.0.0-alpha.1"

[build-dependencies]
protoc-rust = "3.0.0-alpha.1"
