[package]
name = "pancake-db-idl"
version = "0.0.0"
edition = "2018"
build = "src/build.rs"

authors = ["mwlon <m.w.loncaric@gmail.com>"]
description = "API specification for PancakeDB"
exclude = ["src/build.rs"]
keywords = ["pancake", "idl", "protobuf"]
license = "Apache-2.0"
repository = "https://github.com/pancake-db/pancake-idl/"

[dependencies]
protobuf = {git="https://github.com/stepancheg/rust-protobuf", rev="b3fe22932968995779e4046189becdf7be82ba1d", version="3.0.0-pre"}

[build-dependencies]
protoc-rust = {git="https://github.com/stepancheg/rust-protobuf", rev="b3fe22932968995779e4046189becdf7be82ba1d", version="3.0.0-pre"}
